const questions = [
  {
    id: 1,
    question: "The company increased its (　) to improve short-term liquidity.",
    translation: "会社は短期的な流動性を改善するため（　）を増やした。",
    choices: ["Cash and deposits", "Marketable securities", "Short-term loans receivable"],
    meanings: ["現金及び預金", "有価証券", "短期貸付金"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産',
    explanation: '「短期的な流動性」とは即座に支払いに使える資金を指し、現金及び預金が最も流動性が高い。有価証券は換金に時間を要し、短期貸付金は回収まで期間がある。'
  },
  {
    id: 2,
    question: "The company purchased (　) as a short-term investment with the intention to sell within one year.",
    translation: "会社は1年以内に売却する意図で短期投資として（　）を購入した。",
    choices: ["Marketable securities", "Investment securities", "Cash and deposits"],
    meanings: ["有価証券", "投資有価証券", "現金及び預金"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産',
    explanation: '1年以内に売却予定の株式や債券は流動資産の「有価証券」。1年超保有予定は固定資産の「投資有価証券」。現金及び預金は投資ではない。'
  },
  {
    id: 3,
    question: "The company holds (　) as negotiable instruments received from customers with maturity dates.",
    translation: "会社は顧客から受け取った満期日のある流通可能な証券として（　）を保有している。",
    choices: ["Notes receivable - trade", "Accounts receivable - trade", "Accounts receivable - other"],
    meanings: ["受取手形", "売掛金", "未収入金"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産',
    explanation: '約束手形や為替手形など証券形式で受け取った営業上の債権は「受取手形」。証券形式でない掛売りは「売掛金」、営業外取引は「未収入金」。'
  },
  {
    id: 4,
    question: "Sales on credit to customers are recorded as (　) until cash is collected.",
    translation: "顧客への掛売上は現金回収まで（　）として計上される。",
    choices: ["Accounts receivable - trade", "Notes receivable - trade", "Accrued revenue"],
    meanings: ["売掛金", "受取手形", "未収収益"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産',
    explanation: '商品・製品の掛売りによる営業債権は「売掛金」。手形で受け取った場合は「受取手形」、役務提供で未収のものは「未収収益」。'
  },
  {
    id: 5,
    question: "Interest earned on loans but not yet received at the balance sheet date is recognized as (　).",
    translation: "貸付金の利息で決算日までに発生しているが未受取のものは（　）として認識される。",
    choices: ["Accrued revenue", "Accounts receivable - other", "Interest income"],
    meanings: ["未収収益", "未収入金", "受取利息"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産',
    explanation: '継続的な役務提供で決算日までに発生しているが未収の収益は「未収収益」（発生主義）。未収入金は営業外の単発債権、受取利息は損益計算書の収益科目。'
  },
  {
    id: 6,
    question: "Materials purchased and held for production are classified as (　).",
    translation: "生産のために購入し保有している材料は（　）として分類される。",
    choices: ["Raw materials", "Work in process", "Finished goods"],
    meanings: ["原材料", "仕掛品", "製品"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産',
    explanation: '製造業で未加工の材料は「原材料」。加工中のものは「仕掛品」、完成品は「製品」。商品売買業では「商品」を使用。'
  },
  {
    id: 7,
    question: "Merchandise purchased for resale by a retail company is recorded as (　).",
    translation: "小売業が転売目的で購入した商品は（　）として記録される。",
    choices: ["Merchandise", "Raw materials", "Finished goods"],
    meanings: ["商品", "原材料", "製品"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産',
    explanation: '商品売買業の棚卸資産は「商品」。製造業では「原材料」「仕掛品」「製品」を区分。完成した自社製品は「製品」。'
  },
  {
    id: 8,
    question: "Products in the manufacturing process that are not yet completed are classified as (　).",
    translation: "製造過程にあり未完成の製品は（　）として分類される。",
    choices: ["Work in process", "Raw materials", "Finished goods"],
    meanings: ["仕掛品", "原材料", "製品"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産',
    explanation: '製造途中の半製品は「仕掛品」。未加工の材料は「原材料」、完成品は「製品」。'
  },
  {
    id: 9,
    question: "Completed products ready for sale held by a manufacturing company are recorded as (　).",
    translation: "製造業が保有する販売可能な完成品は（　）として記録される。",
    choices: ["Finished goods", "Merchandise", "Work in process"],
    meanings: ["製品", "商品", "仕掛品"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産',
    explanation: '自社製造の完成品は「製品」。他社から仕入れた転売品は「商品」、製造途中は「仕掛品」。'
  },
  {
    id: 10,
    question: "The allowance for estimated uncollectible receivables is recorded as (　).",
    translation: "回収不能と見込まれる債権の引当額は（　）として記録される。",
    choices: ["Allowance for doubtful accounts", "Bad debt expenses", "Provision for bonuses"],
    meanings: ["貸倒引当金", "貸倒損失", "賞与引当金"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産',
    explanation: '将来の貸倒れに備える評価性引当金は「貸倒引当金」（資産のマイナス）。実際に回収不能になった費用は「貸倒損失」、賞与引当金は負債科目。'
  },
  {
    id: 11,
    question: "Structures used for business operations such as offices and factories are recorded as (　).",
    translation: "事務所や工場など事業用の建造物は（　）として記録される。",
    choices: ["Buildings", "Structures", "Land"],
    meanings: ["建物", "構築物", "土地"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産',
    explanation: '屋根と壁がある建造物は「建物」。土地に定着した建物以外の工作物（塀、舗装等）は「構築物」、土地そのものは「土地」。'
  },
  {
    id: 12,
    question: "Structures attached to land such as bridges, fences, and pavement are classified as (　).",
    translation: "橋、塀、舗装など土地に定着した構造物は（　）として分類される。",
    choices: ["Structures", "Buildings", "Machinery and equipment"],
    meanings: ["構築物", "建物", "機械装置"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産',
    explanation: '建物以外の土地定着物は「構築物」。屋根と壁のある建造物は「建物」、生産設備は「機械装置」。'
  },
  {
    id: 13,
    question: "Manufacturing equipment used in the production process is classified as (　).",
    translation: "生産工程で使用される製造設備は（　）として分類される。",
    choices: ["Machinery and equipment", "Tools, furniture and fixtures", "Vehicles"],
    meanings: ["機械装置", "工具器具備品", "車両運搬具"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産',
    explanation: '製造ラインの大型機械は「機械装置」。小型の工具や備品は「工具器具備品」、運搬用車両は「車両運搬具」。'
  },
  {
    id: 14,
    question: "Office furniture, computers, and small tools are recorded as (　).",
    translation: "事務机、パソコン、小型工具は（　）として記録される。",
    choices: ["Tools, furniture and fixtures", "Machinery and equipment", "Supplies"],
    meanings: ["工具器具備品", "機械装置", "貯蔵品"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産',
    explanation: '比較的小型の器具・備品は「工具器具備品」。大型生産設備は「機械装置」、消耗品は「貯蔵品」。'
  },
  {
    id: 15,
    question: "Real property owned by the company for business use is recorded as (　).",
    translation: "会社が事業用に所有する不動産は（　）として記録される。",
    choices: ["Land", "Buildings", "Structures"],
    meanings: ["土地", "建物", "構築物"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産',
    explanation: '土地そのものは「土地」（非償却資産）。建物は「建物」、土地定着物は「構築物」（いずれも償却資産）。'
  },
  {
    id: 16,
    question: "Costs incurred for assets under construction are temporarily recorded as (　) until completion.",
    translation: "建設中の資産に関する支出は完成まで一時的に（　）として記録される。",
    choices: ["Construction in progress", "Buildings", "Advance payments"],
    meanings: ["建設仮勘定", "建物", "前払金"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産',
    explanation: '建設中の固定資産への支出は「建設仮勘定」。完成時に本勘定（建物等）に振替。通常の前払いは「前払金」。'
  },
  {
    id: 17,
    question: "The total accumulated depreciation deducted from the acquisition cost of assets is shown as (　).",
    translation: "資産の取得原価から控除される減価償却の累計額は（　）として表示される。",
    choices: ["Accumulated depreciation", "Depreciation", "Impairment losses"],
    meanings: ["減価償却累計額", "減価償却費", "減損損失"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産',
    explanation: '過去の減価償却費の累計額は「減価償却累計額」（資産のマイナス科目）。当期の費用は「減価償却費」、資産価値の臨時的下落は「減損損失」。'
  },
  {
    id: 18,
    question: "Computer programs developed or purchased for internal business use are capitalized as (　).",
    translation: "社内業務用に開発または購入したコンピュータプログラムは（　）として資産計上される。",
    choices: ["Software", "Patent right", "Goodwill"],
    meanings: ["ソフトウェア", "特許権", "のれん"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産',
    explanation: 'コンピュータプログラムは無形固定資産の「ソフトウェア」。発明の権利は「特許権」、企業買収のプレミアムは「のれん」。'
  },
  {
    id: 19,
    question: "The excess of the purchase price over the fair value of net assets acquired in a business combination is recorded as (　).",
    translation: "企業結合において取得対価が取得純資産の公正価値を上回る部分は（　）として記録される。",
    choices: ["Goodwill", "Intangible assets", "Investment securities"],
    meanings: ["のれん", "無形固定資産", "投資有価証券"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産',
    explanation: 'M&Aでの超過収益力は「のれん」（日本基準では20年以内に償却）。特許権等は「無形固定資産」の個別科目、株式投資は「投資有価証券」。'
  },
  {
    id: 20,
    question: "Exclusive rights to inventions granted by the government are recorded as (　).",
    translation: "政府により付与された発明の独占権は（　）として記録される。",
    choices: ["Patent right", "Trademark right", "Software"],
    meanings: ["特許権", "商標権", "ソフトウェア"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産',
    explanation: '発明の独占権は「特許権」。ブランド名等は「商標権」、コンピュータプログラムは「ソフトウェア」。'
  },
  {
    id: 21,
    question: "Exclusive rights to distinctive brand names and symbols are recorded as (　).",
    translation: "独占的なブランド名やシンボルの権利は（　）として記録される。",
    choices: ["Trademark right", "Patent right", "Goodwill"],
    meanings: ["商標権", "特許権", "のれん"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産',
    explanation: 'ブランド名・ロゴ等の使用独占権は「商標権」。発明の権利は「特許権」、買収プレミアムは「のれん」。'
  },
  {
    id: 22,
    question: "Long-term equity investments in other companies held for strategic purposes are classified as (　).",
    translation: "戦略目的で保有する他社への長期株式投資は（　）として分類される。",
    choices: ["Investment securities", "Marketable securities", "Shares of subsidiaries and associates"],
    meanings: ["投資有価証券", "有価証券", "関係会社株式"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産',
    explanation: '1年超保有の戦略的投資は「投資有価証券」。1年以内売却予定は「有価証券」、子会社・関連会社株式は「関係会社株式」で別掲。'
  },
  {
    id: 23,
    question: "Payments to suppliers for goods purchased on credit are recorded as (　).",
    translation: "仕入先への掛仕入れ代金の支払債務は（　）として記録される。",
    choices: ["Accounts payable - trade", "Notes payable - trade", "Accounts payable - other"],
    meanings: ["買掛金", "支払手形", "未払金"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '負債',
    explanation: '営業取引の掛仕入れ債務は「買掛金」。手形で支払う場合は「支払手形」、営業外取引は「未払金」。'
  },
  {
    id: 24,
    question: "Promissory notes or bills of exchange issued to suppliers are classified as (　).",
    translation: "仕入先に対して発行した約束手形や為替手形は（　）として分類される。",
    choices: ["Notes payable - trade", "Accounts payable - trade", "Short-term borrowings"],
    meanings: ["支払手形", "買掛金", "短期借入金"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '負債',
    explanation: '営業取引で発行した手形債務は「支払手形」。手形以外の掛仕入れは「買掛金」、金融機関からの借入は「短期借入金」。'
  },
  {
    id: 25,
    question: "Loans from financial institutions due within one year are recorded as (　).",
    translation: "金融機関からの1年以内返済予定の借入金は（　）として記録される。",
    choices: ["Short-term borrowings", "Long-term borrowings", "Notes payable - trade"],
    meanings: ["短期借入金", "長期借入金", "支払手形"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '負債',
    explanation: '1年以内返済の借入金は「短期借入金」。1年超は「長期借入金」、営業取引の手形は「支払手形」。'
  },
  {
    id: 26,
    question: "The portion of long-term debt due within one year from the balance sheet date is reclassified as (　).",
    translation: "長期借入金のうち決算日から1年以内に返済期限が到来する部分は（　）に振り替えられる。",
    choices: ["Current portion of long-term borrowings", "Short-term borrowings", "Long-term borrowings"],
    meanings: ["1年内返済予定の長期借入金", "短期借入金", "長期借入金"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '負債',
    explanation: '長期借入金の1年以内返済分は流動負債の「1年内返済予定の長期借入金」に振替。当初から短期の借入は「短期借入金」。'
  },
  {
    id: 27,
    question: "Obligations for goods or services received but not yet invoiced are recorded as (　).",
    translation: "商品やサービスを受領したが請求書未到達の債務は（　）として記録される。",
    choices: ["Accounts payable - other", "Accounts payable - trade", "Accrued expenses"],
    meanings: ["未払金", "買掛金", "未払費用"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '負債',
    explanation: '固定資産購入等の営業外取引の未払債務は「未払金」。営業上の仕入債務は「買掛金」、継続的役務の未払いは「未払費用」。'
  },
  {
    id: 28,
    question: "Accrued but unpaid expenses for ongoing services such as rent and utilities are classified as (　).",
    translation: "賃借料や光熱費など継続的サービスの発生済み未払費用は（　）として分類される。",
    choices: ["Accrued expenses", "Accounts payable - other", "Accounts payable - trade"],
    meanings: ["未払費用", "未払金", "買掛金"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '負債',
    explanation: '時間の経過により継続的に発生する未払費用は「未払費用」（発生主義）。単発の営業外取引は「未払金」、営業債務は「買掛金」。'
  },
  {
    id: 29,
    question: "Payments received from customers before goods are delivered or services are performed are recorded as (　).",
    translation: "商品引渡し前またはサービス提供前に顧客から受け取った代金は（　）として記録される。",
    choices: ["Advances received", "Deposits received", "Unearned revenue"],
    meanings: ["前受金", "預り金", "前受収益"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '負債',
    explanation: '商品・サービス提供前の受取額は「前受金」。一時的な預り（税金等）は「預り金」、継続的役務の前受けは「前受収益」。'
  },
  {
    id: 30,
    question: "Amounts collected from customers for employee income taxes and social insurance are temporarily held as (　).",
    translation: "従業員の所得税や社会保険料として顧客から預かった金額は一時的に（　）として保管される。",
    choices: ["Deposits received", "Advances received", "Accrued expenses"],
    meanings: ["預り金", "前受金", "未払費用"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '負債',
    explanation: '第三者のために一時的に預かる金銭は「預り金」（源泉税、社会保険料等）。商品引渡し前の受取は「前受金」、自社の未払いは「未払費用」。'
  },
  {
    id: 31,
    question: "Revenue received in advance for services to be provided over time is recognized as (　).",
    translation: "継続的に提供するサービスの前受収益は（　）として認識される。",
    choices: ["Unearned revenue", "Advances received", "Deposits received"],
    meanings: ["前受収益", "前受金", "預り金"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '負債',
    explanation: '時間の経過により実現する収益の前受分は「前受収益」（発生主義）。単発取引の前受けは「前受金」、預り金は「預り金」。'
  },
  {
    id: 32,
    question: "Estimated liabilities for future bonus payments to employees are recorded as (　).",
    translation: "従業員への将来の賞与支払いに備えた見積負債は（　）として記録される。",
    choices: ["Provision for bonuses", "Accrued expenses", "Retirement benefit liability"],
    meanings: ["賞与引当金", "未払費用", "退職給付に係る負債"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '負債',
    explanation: '賞与支給見込額のうち当期負担分は「賞与引当金」。既に確定した未払分は「未払費用」、退職給付債務は「退職給付に係る負債」。'
  },
  {
    id: 33,
    question: "Loans from financial institutions with repayment terms exceeding one year are classified as (　).",
    translation: "金融機関からの返済期間が1年を超える借入金は（　）として分類される。",
    choices: ["Long-term borrowings", "Short-term borrowings", "Bonds payable"],
    meanings: ["長期借入金", "短期借入金", "社債"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '負債',
    explanation: '1年超の借入金は「長期借入金」。1年以内は「短期借入金」、債券発行は「社債」。ワンイヤールール適用。'
  },
  {
    id: 34,
    question: "Debt securities issued by the company to raise long-term capital are recorded as (　).",
    translation: "長期資金調達のために会社が発行した債券は（　）として記録される。",
    choices: ["Bonds payable", "Long-term borrowings", "Short-term borrowings"],
    meanings: ["社債", "長期借入金", "短期借入金"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '負債',
    explanation: '不特定多数の投資家向けに発行する債券は「社債」。金融機関からの借入は「長期借入金」または「短期借入金」。'
  },
  {
    id: 35,
    question: "Obligations for employee retirement benefits calculated using actuarial methods are shown as (　).",
    translation: "数理計算により算定された従業員の退職給付債務は（　）として表示される。",
    choices: ["Retirement benefit liability", "Provision for bonuses", "Accrued expenses"],
    meanings: ["退職給付に係る負債", "賞与引当金", "未払費用"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '負債',
    explanation: '退職給付債務から年金資産を控除した額は「退職給付に係る負債」。賞与は「賞与引当金」、通常の未払いは「未払費用」。'
  },
  {
    id: 36,
    question: "Estimated future warranty costs for products sold are recognized as (　).",
    translation: "販売した製品の将来の保証費用見積額は（　）として認識される。",
    choices: ["Provision for product warranties", "Accrued expenses", "Provision for bonuses"],
    meanings: ["製品保証引当金", "未払費用", "賞与引当金"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '負債',
    explanation: '製品保証による将来の費用負担見込額は「製品保証引当金」。既に発生した未払いは「未払費用」、賞与は「賞与引当金」。'
  },
  {
    id: 37,
    question: "Corporate income taxes calculated on taxable income but not yet paid are recorded as (　).",
    translation: "課税所得に基づき計算された未払法人税等は（　）として記録される。",
    choices: ["Income taxes payable", "Deferred tax liabilities", "Accrued expenses"],
    meanings: ["未払法人税等", "繰延税金負債", "未払費用"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '負債',
    explanation: '当期の法人税・住民税・事業税の未払額は「未払法人税等」。税効果会計の負債は「繰延税金負債」、通常の未払いは「未払費用」。'
  },
  {
    id: 38,
    question: "Consumption taxes collected from customers but not yet remitted to tax authorities are shown as (　).",
    translation: "顧客から預かったが税務当局に未納付の消費税等は（　）として表示される。",
    choices: ["Accrued consumption taxes", "Income taxes payable", "Deposits received"],
    meanings: ["未払消費税等", "未払法人税等", "預り金"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '負債',
    explanation: '仮受消費税から仮払消費税を控除した納付額は「未払消費税等」。法人税等は「未払法人税等」、一般的な預りは「預り金」。'
  },
  {
    id: 39,
    question: "Funds contributed by shareholders in exchange for ownership shares are recorded as (　).",
    translation: "株主が出資した資金は株式の対価として（　）に記録される。",
    choices: ["Share capital", "Capital surplus", "Retained earnings"],
    meanings: ["資本金", "資本剰余金", "利益剰余金"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '純資産',
    explanation: '株式発行による払込額のうち会社法上資本金とした額は「資本金」。資本金を超える部分は「資本剰余金」、稼得利益は「利益剰余金」。'
  },
  {
    id: 40,
    question: "The excess of share issuance proceeds over the par value is classified as (　).",
    translation: "株式発行による払込額のうち額面を超える部分は（　）として分類される。",
    choices: ["Capital surplus", "Share capital", "Retained earnings"],
    meanings: ["資本剰余金", "資本金", "利益剰余金"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '純資産',
    explanation: '払込額のうち資本金としなかった部分は「資本剰余金」（資本準備金等）。資本金組入額は「資本金」、稼得利益は「利益剰余金」。'
  },
  {
    id: 41,
    question: "Accumulated profits retained in the business and not distributed to shareholders are classified as (　).",
    translation: "事業に留保され株主に配分されていない累積利益は（　）として分類される。",
    choices: ["Retained earnings", "Share capital", "Capital surplus"],
    meanings: ["利益剰余金", "資本金", "資本剰余金"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '純資産',
    explanation: '過去の利益の蓄積は「利益剰余金」（利益準備金+その他利益剰余金）。出資は「資本金」「資本剰余金」。'
  },
  {
    id: 42,
    question: "Amounts legally required to be set aside from profits are recorded as (　).",
    translation: "法律により利益から積み立てが義務付けられた金額は（　）として記録される。",
    choices: ["Legal reserve", "Retained earnings brought forward", "Voluntary reserve"],
    meanings: ["利益準備金", "繰越利益剰余金", "任意積立金"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '純資産',
    explanation: '配当時に積立が強制される準備金は「利益準備金」（会社法）。任意の積立ては「任意積立金」、未処分利益は「繰越利益剰余金」。'
  },
  {
    id: 43,
    question: "Own shares repurchased by the company from shareholders are shown as (　).",
    translation: "会社が株主から買い戻した自社株式は（　）として表示される。",
    choices: ["Treasury shares", "Share capital", "Investment securities"],
    meanings: ["自己株式", "資本金", "投資有価証券"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '純資産',
    explanation: '自社株式の取得は「自己株式」（純資産のマイナス項目）。発行時の資本金は「資本金」、他社株式は「投資有価証券」。'
  },
  {
    id: 44,
    question: "Revenue from the primary business activities of selling goods or services is recorded as (　).",
    translation: "商品・サービス販売という主たる事業活動による収益は（　）として記録される。",
    choices: ["Net sales", "Operating revenue", "Non-operating income"],
    meanings: ["売上高", "営業収益", "営業外収益"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '収益',
    explanation: '商品・製品の販売収益は「売上高」。サービス業は「営業収益」を使う場合も。営業外の収益は「営業外収益」。'
  },
  {
    id: 45,
    question: "The direct costs of producing or purchasing goods sold during the period are shown as (　).",
    translation: "当期に販売された商品の製造または購入に係る直接原価は（　）として表示される。",
    choices: ["Cost of sales", "Selling, general and administrative expenses", "Operating expenses"],
    meanings: ["売上原価", "販売費及び一般管理費", "営業費用"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用',
    explanation: '売上に対応する商品・製品の原価は「売上原価」。販売・管理活動の費用は「販売費及び一般管理費」。'
  },
  {
    id: 46,
    question: "Costs related to selling activities and general administration are classified as (　).",
    translation: "販売活動及び一般管理に関する費用は（　）として分類される。",
    choices: ["Selling, general and administrative expenses", "Cost of sales", "Non-operating expenses"],
    meanings: ["販売費及び一般管理費", "売上原価", "営業外費用"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用',
    explanation: '販売・管理部門の人件費、広告費、減価償却費等は「販売費及び一般管理費」。商品原価は「売上原価」、営業外は「営業外費用」。'
  },
  {
    id: 47,
    question: "The systematic allocation of tangible asset costs over their useful lives is recorded as (　).",
    translation: "有形固定資産の取得原価を耐用年数にわたり組織的に配分する費用は（　）として記録される。",
    choices: ["Depreciation", "Accumulated depreciation", "Impairment losses"],
    meanings: ["減価償却費", "減価償却累計額", "減損損失"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用',
    explanation: '当期の減価償却費用は「減価償却費」（費用科目）。過去の累計は「減価償却累計額」（資産のマイナス）、臨時的下落は「減損損失」。'
  },
  {
    id: 48,
    question: "Interest earned on bank deposits, loans receivable, and bonds is shown as (　).",
    translation: "銀行預金、貸付金、債券から生じる利息は（　）として表示される。",
    choices: ["Interest income", "Dividend income", "Net sales"],
    meanings: ["受取利息", "受取配当金", "売上高"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '収益',
    explanation: '預金・貸付金等から生じる利息収益は「受取利息」（営業外収益）。株式からの配当は「受取配当金」、本業収益は「売上高」。'
  },
  {
    id: 49,
    question: "Distributions received from equity investments in stocks are recorded as (　).",
    translation: "株式への投資から受け取る配当金は（　）として記録される。",
    choices: ["Dividend income", "Interest income", "Gain on sale of investment securities"],
    meanings: ["受取配当金", "受取利息", "投資有価証券売却益"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '収益',
    explanation: '株式投資からの配当は「受取配当金」（営業外収益）。債券利息は「受取利息」、株式売却益は「投資有価証券売却益」。'
  },
  {
    id: 50,
    question: "Interest paid on borrowings and bonds is classified as (　).",
    translation: "借入金及び社債に対して支払う利息は（　）として分類される。",
    choices: ["Interest expenses", "Commission expenses", "Bond issuance costs"],
    meanings: ["支払利息", "支払手数料", "社債発行費"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用',
    explanation: '借入金・社債の利息費用は「支払利息」（営業外費用）。手数料は「支払手数料」、社債発行時の費用は「社債発行費」。'
  },
  {
    id: 51,
    question: "Gains from favorable foreign currency exchange rate movements are shown as (　).",
    translation: "有利な外国為替レート変動による利益は（　）として表示される。",
    choices: ["Foreign exchange gains", "Interest income", "Gain on sale of investment securities"],
    meanings: ["為替差益", "受取利息", "投資有価証券売却益"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '収益',
    explanation: '外貨建取引・外貨建資産負債の換算による利益は「為替差益」（営業外収益）。利息は「受取利息」、有価証券売却益は別科目。'
  },
  {
    id: 52,
    question: "Losses from unfavorable foreign currency exchange rate movements are recorded as (　).",
    translation: "不利な外国為替レート変動による損失は（　）として記録される。",
    choices: ["Foreign exchange losses", "Interest expenses", "Loss on valuation of investment securities"],
    meanings: ["為替差損", "支払利息", "投資有価証券評価損"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用',
    explanation: '外貨建取引・外貨建資産負債の換算による損失は「為替差損」（営業外費用）。利息費用や有価証券評価損は別科目。'
  },
  {
    id: 53,
    question: "Profits from selling tangible fixed assets above their book value are shown as (　).",
    translation: "有形固定資産を帳簿価額を上回る価格で売却した利益は（　）として表示される。",
    choices: ["Gain on sale of property, plant and equipment", "Gain on sale of investment securities", "Interest income"],
    meanings: ["固定資産売却益", "投資有価証券売却益", "受取利息"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '収益',
    explanation: '建物・機械等の売却益は「固定資産売却益」（特別利益）。投資有価証券の売却益は別科目、利息は営業外収益。'
  },
  {
    id: 54,
    question: "Losses from selling tangible fixed assets below their book value are recorded as (　).",
    translation: "有形固定資産を帳簿価額を下回る価格で売却した損失は（　）として記録される。",
    choices: ["Loss on sale of property, plant and equipment", "Loss on retirement of property, plant and equipment", "Impairment losses"],
    meanings: ["固定資産売却損", "固定資産除却損", "減損損失"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用',
    explanation: '固定資産の売却損は「固定資産売却損」（特別損失）。廃棄・除却は「固定資産除却損」、使用価値の下落は「減損損失」。'
  },
  {
    id: 55,
    question: "Losses from discarding or scrapping fixed assets are shown as (　).",
    translation: "固定資産を廃棄または除却した際の損失は（　）として表示される。",
    choices: ["Loss on retirement of property, plant and equipment", "Loss on sale of property, plant and equipment", "Depreciation"],
    meanings: ["固定資産除却損", "固定資産売却損", "減価償却費"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用',
    explanation: '固定資産を廃棄・除却した損失は「固定資産除却損」（特別損失）。売却損は「固定資産売却損」、通常の償却は「減価償却費」。'
  },
  {
    id: 56,
    question: "Write-downs of asset carrying amounts to their recoverable amounts are recorded as (　).",
    translation: "資産の帳簿価額を回収可能価額まで減額する損失は（　）として記録される。",
    choices: ["Impairment losses", "Depreciation", "Loss on retirement of property, plant and equipment"],
    meanings: ["減損損失", "減価償却費", "固定資産除却損"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用',
    explanation: '資産の収益性低下による臨時的な簿価切下げは「減損損失」（特別損失）。規則的償却は「減価償却費」、除却は「固定資産除却損」。'
  },
  {
    id: 57,
    question: "Receivables that have been determined to be uncollectible are written off as (　).",
    translation: "回収不能と確定した債権の貸倒れは（　）として償却される。",
    choices: ["Bad debt expenses", "Allowance for doubtful accounts", "Loss on valuation of investment securities"],
    meanings: ["貸倒損失", "貸倒引当金", "投資有価証券評価損"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用',
    explanation: '回収不能が確定した債権の損失は「貸倒損失」（特別損失または営業外費用）。事前の見積りは「貸倒引当金」（資産のマイナス）。'
  },
  {
    id: 58,
    question: "Regular monthly or annual compensation paid to employees is recorded as (　).",
    translation: "従業員に支払う定期的な月給または年俸は（　）として記録される。",
    choices: ["Salaries and wages", "Bonuses", "Retirement benefit expenses"],
    meanings: ["給料及び手当", "賞与", "退職給付費用"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用',
    explanation: '定期的な給与・諸手当は「給料及び手当」（販管費）。賞与は「賞与」、退職給付は「退職給付費用」で別掲。'
  },
  {
    id: 59,
    question: "Performance-based or periodic additional compensation to employees is shown as (　).",
    translation: "従業員への業績連動または定期的な追加報酬は（　）として表示される。",
    choices: ["Bonuses", "Salaries and wages", "Provision for bonuses"],
    meanings: ["賞与", "給料及び手当", "賞与引当金"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用',
    explanation: '支給確定した賞与は「賞与」（費用）。定期給与は「給料及び手当」、将来支給見込額の引当ては「賞与引当金」（負債）。'
  },
  {
    id: 60,
    question: "Employer contributions to social insurance programs are classified as (　).",
    translation: "社会保険制度への事業主負担分は（　）として分類される。",
    choices: ["Statutory welfare expenses", "Welfare expenses", "Retirement benefit expenses"],
    meanings: ["法定福利費", "福利厚生費", "退職給付費用"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用',
    explanation: '健康保険・厚生年金等の法定社会保険料は「法定福利費」。任意の福利厚生は「福利厚生費」、退職給付は別科目。'
  },
  {
    id: 61,
    question: "Voluntary employee benefits such as cafeterias and recreational facilities are classified as (　).",
    translation: "食堂や厚生施設など任意の従業員給付は（　）として分類される。",
    choices: ["Welfare expenses", "Statutory welfare expenses", "Salaries and wages"],
    meanings: ["福利厚生費", "法定福利費", "給料及び手当"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用',
    explanation: '法定外の任意福利厚生（社宅、慶弔見舞金等）は「福利厚生費」。社会保険料は「法定福利費」、給与は「給料及び手当」。'
  },
  {
    id: 62,
    question: "Expenses incurred for retirement benefits earned by employees during the period are shown as (　).",
    translation: "当期に従業員が獲得した退職給付に関する費用は（　）として表示される。",
    choices: ["Retirement benefit expenses", "Provision for bonuses", "Statutory welfare expenses"],
    meanings: ["退職給付費用", "賞与引当金", "法定福利費"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用',
    explanation: '退職給付債務の当期増加額等は「退職給付費用」（販管費）。賞与引当ては別科目、社会保険料は「法定福利費」。'
  },
  {
    id: 63,
    question: "Costs for business trips including transportation and lodging are recorded as (　).",
    translation: "交通費や宿泊費を含む出張費用は（　）として記録される。",
    choices: ["Travel and transportation expenses", "Entertainment expenses", "Meeting expenses"],
    meanings: ["旅費交通費", "接待交際費", "会議費"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用',
    explanation: '出張旅費・交通費・宿泊費は「旅費交通費」。接待費用は「接待交際費」、会議関連費は「会議費」。'
  },
  {
    id: 64,
    question: "Costs for telephone, internet, and postal services are classified as (　).",
    translation: "電話、インターネット、郵便サービスの費用は（　）として分類される。",
    choices: ["Communication expenses", "Utilities", "Supplies expenses"],
    meanings: ["通信費", "水道光熱費", "消耗品費"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用',
    explanation: '電話・ネット・郵便は「通信費」。電気・ガス・水道は「水道光熱費」、事務用品は「消耗品費」。'
  },
  {
    id: 65,
    question: "Costs for electricity, gas, and water consumed in business operations are shown as (　).",
    translation: "事業活動で消費する電気、ガス、水道の費用は（　）として表示される。",
    choices: ["Utilities", "Communication expenses", "Rent expenses"],
    meanings: ["水道光熱費", "通信費", "地代家賃"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用',
    explanation: '電気・ガス・水道の料金は「水道光熱費」。電話等は「通信費」、賃借料は「地代家賃」。'
  },
  {
    id: 66,
    question: "Expenditures for promoting products through media and other channels are recorded as (　).",
    translation: "メディア等を通じた製品プロモーションの支出は（　）として記録される。",
    choices: ["Advertising expenses", "Sales promotion expenses", "Entertainment expenses"],
    meanings: ["広告宣伝費", "販売促進費", "接待交際費"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用',
    explanation: 'メディア広告・宣伝活動は「広告宣伝費」。店頭プロモーションは「販売促進費」、接待は「接待交際費」。'
  },
  {
    id: 67,
    question: "Costs for entertaining clients and business partners are classified as (　).",
    translation: "顧客や取引先を接待する費用は（　）として分類される。",
    choices: ["Entertainment expenses", "Advertising expenses", "Meeting expenses"],
    meanings: ["接待交際費", "広告宣伝費", "会議費"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用',
    explanation: '取引先への接待・贈答は「接待交際費」（税務上損金算入限度額あり）。広告は「広告宣伝費」、会議費用は「会議費」。'
  },
  {
    id: 68,
    question: "Property taxes, stamp duties, and other non-income-based taxes are shown as (　).",
    translation: "固定資産税、印紙税、その他の所得ベースでない税金は（　）として表示される。",
    choices: ["Taxes and dues", "Income taxes payable", "Accrued consumption taxes"],
    meanings: ["租税公課", "未払法人税等", "未払消費税等"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用',
    explanation: '固定資産税・印紙税・事業税等は「租税公課」（販管費）。法人税等は「未払法人税等」（負債）、消費税は別科目。'
  },
  {
    id: 165,
    question: "Premiums paid for fire, liability, and other business insurance coverage are recorded as (　).",
    translation: "火災、賠償責任、その他の事業保険の保険料は（　）として記録される。",
    choices: ["Insurance expenses", "Statutory welfare expenses", "Taxes and dues"],
    meanings: ["保険料", "法定福利費", "租税公課"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用',
    explanation: '損害保険料は「保険料」（販管費）。社会保険料は「法定福利費」、税金は「租税公課」。'
  },
  {
    id: 166,
    question: "Costs for maintaining, fixing, and repairing tangible assets are classified as (　).",
    translation: "有形固定資産の維持、修理、補修費用は（　）として分類される。",
    choices: ["Repair and maintenance expenses", "Depreciation", "Capital expenditures"],
    meanings: ["修繕費", "減価償却費", "資本的支出"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用',
    explanation: '原状回復の修繕は「修繕費」（費用）。規則的償却は「減価償却費」、性能向上・耐用年数延長は資本的支出（資産計上）。'
  },
  {
    id: 167,
    question: "Office supplies, stationery, and other consumable items used in daily operations are shown as (　).",
    translation: "日常業務で使用する事務用品、文房具、その他消耗品は（　）として表示される。",
    choices: ["Supplies expenses", "Supplies", "Miscellaneous expenses"],
    meanings: ["消耗品費", "貯蔵品", "雑費"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用',
    explanation: '購入時に費用処理する少額消耗品は「消耗品費」。未使用分を資産計上する場合は「貯蔵品」、その他は「雑費」。'
  },
  {
    id: 168,
    question: "Rental payments for office buildings, land, and equipment are recorded as (　).",
    translation: "事務所建物、土地、設備の賃借料は（　）として記録される。",
    choices: ["Rent expenses", "Depreciation", "Repair and maintenance expenses"],
    meanings: ["地代家賃", "減価償却費", "修繕費"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用',
    explanation: '土地・建物の賃借料は「地代家賃」。自己所有資産の償却は「減価償却費」、修理は「修繕費」。'
  },
  {
    id: 169,
    question: "Fees paid to lawyers, accountants, and consultants are classified as (　).",
    translation: "弁護士、会計士、コンサルタントに支払う報酬は（　）として分類される。",
    choices: ["Commission and professional fees", "Salaries and wages", "Outsourcing expenses"],
    meanings: ["支払手数料", "給料及び手当", "外注費"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用',
    explanation: '専門家報酬・金融手数料等は「支払手数料」。従業員給与は「給料及び手当」、外部委託は「外注費」。'
  },
  {
    id: 170,
    question: "Costs incurred for developing new products and technologies are shown as (　).",
    translation: "新製品・新技術の開発に係る費用は（　）として表示される。",
    choices: ["Research and development expenses", "Advertising expenses", "Software"],
    meanings: ["研究開発費", "広告宣伝費", "ソフトウェア"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用',
    explanation: '研究開発活動の費用は「研究開発費」（発生時費用処理が原則）。広告は別科目、販売目的ソフトウェアは資産計上可能。'
  },
  {
    id: 171,
    question: "Uncollectible accounts receivable that are definitively written off are recorded as (　).",
    translation: "回収不能が確定し償却された売掛金等は（　）として記録される。",
    choices: ["Bad debt losses", "Allowance for doubtful accounts", "Loss on valuation of investment securities"],
    meanings: ["貸倒損失", "貸倒引当金", "投資有価証券評価損"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用',
    explanation: '回収不能確定時の債権償却は「貸倒損失」（費用）。将来の貸倒見積りは「貸倒引当金」（資産のマイナス）。'
  },
  {
    id: 172,
    question: "Costs that cannot be clearly classified into other specific expense categories are shown as (　).",
    translation: "他の特定費用科目に明確に分類できない費用は（　）として表示される。",
    choices: ["Miscellaneous expenses", "Supplies expenses", "Commission and professional fees"],
    meanings: ["雑費", "消耗品費", "支払手数料"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用',
    explanation: '少額で他科目に該当しない費用は「雑費」。消耗品は「消耗品費」、専門家報酬は「支払手数料」。'
  },
  {
    id: 173,
    question: "Payments made in advance for expenses to be recognized in future periods are classified as (　).",
    translation: "将来の期間に認識される費用の前払額は（　）として分類される。",
    choices: ["Prepaid expenses", "Accrued expenses", "Advances paid"],
    meanings: ["前払費用", "未払費用", "前払金"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産',
    explanation: '継続的な役務提供の前払分は「前払費用」（発生主義）。既に発生した未払いは「未払費用」、商品等の手付金は「前払金」。'
  },
  {
    id: 174,
    question: "Consumable supplies purchased but not yet used are recorded as (　).",
    translation: "購入したが未使用の消耗品は（　）として記録される。",
    choices: ["Supplies", "Supplies expenses", "Inventory"],
    meanings: ["貯蔵品", "消耗品費", "棚卸資産"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産',
    explanation: '未使用の消耗品・事務用品等は「貯蔵品」（資産）。使用時に「消耗品費」に振替。商品・製品等は「棚卸資産」。'
  },
  {
    id: 175,
    question: "Deferred tax assets arising from temporary differences that will reduce future tax payments are shown as (　).",
    translation: "将来の税金支払いを減少させる一時差異から生じる繰延税金資産は（　）として表示される。",
    choices: ["Deferred tax assets", "Deferred tax liabilities", "Income taxes payable"],
    meanings: ["繰延税金資産", "繰延税金負債", "未払法人税等"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産',
    explanation: '将来減算一時差異等による税効果は「繰延税金資産」。将来加算一時差異は「繰延税金負債」、当期納税額は「未払法人税等」。'
  },
  {
    id: 176,
    question: "Deferred tax liabilities arising from temporary differences that will increase future tax payments are recorded as (　).",
    translation: "将来の税金支払いを増加させる一時差異から生じる繰延税金負債は（　）として記録される。",
    choices: ["Deferred tax liabilities", "Deferred tax assets", "Income taxes payable"],
    meanings: ["繰延税金負債", "繰延税金資産", "未払法人税等"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '負債',
    explanation: '将来加算一時差異による税効果は「繰延税金負債」。将来減算一時差異は「繰延税金資産」、当期納税額は「未払法人税等」。'
  },
  {
    id: 177,
    question: "Vehicles used for business operations such as delivery trucks and company cars are recorded as (　).",
    translation: "配送トラックや社用車など事業用車両は（　）として記録される。",
    choices: ["Vehicles", "Machinery and equipment", "Tools, furniture and fixtures"],
    meanings: ["車両運搬具", "機械装置", "工具器具備品"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産',
    explanation: '運搬用の車両は「車両運搬具」（償却資産）。製造設備は「機械装置」、小型の器具は「工具器具備品」。'
  },
  {
    id: 178,
    question: "Leasehold improvements made to rented property are classified as (　).",
    translation: "賃借物件に施した内装工事等の改良は（　）として分類される。",
    choices: ["Leasehold improvements", "Buildings", "Repair and maintenance expenses"],
    meanings: ["建物附属設備", "建物", "修繕費"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産',
    explanation: '建物に付属する設備（電気・空調等）は「建物附属設備」。建物本体は「建物」、原状回復の修理は「修繕費」。'
  },
  {
    id: 179,
    question: "Advance payments made for the purchase of fixed assets are temporarily recorded as (　).",
    translation: "固定資産購入のための前払金は一時的に（　）として記録される。",
    choices: ["Advances paid for non-current assets", "Prepaid expenses", "Construction in progress"],
    meanings: ["建設仮払金", "前払費用", "建設仮勘定"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産',
    explanation: '固定資産取得の手付金・中間金は「建設仮払金」。継続的役務の前払いは「前払費用」、建設中の支出は「建設仮勘定」。'
  },
  {
    id: 180,
    question: "Long-term loans made to employees or affiliated companies are shown as (　).",
    translation: "従業員や関係会社への長期貸付金は（　）として表示される。",
    choices: ["Long-term loans receivable", "Short-term loans receivable", "Accounts receivable - other"],
    meanings: ["長期貸付金", "短期貸付金", "未収入金"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産',
    explanation: '1年超の貸付金は「長期貸付金」。1年以内回収は「短期貸付金」、営業外の未収金は「未収入金」。'
  },
  {
    id: 181,
    question: "Security deposits paid for office rent that will be refunded at the end of the lease are recorded as (　).",
    translation: "賃貸契約終了時に返還される事務所賃貸の敷金は（　）として記録される。",
    choices: ["Guarantee deposits", "Prepaid expenses", "Long-term loans receivable"],
    meanings: ["差入保証金", "前払費用", "長期貸付金"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産',
    explanation: '返還される敷金・保証金は「差入保証金」（投資その他の資産）。賃料の前払いは「前払費用」、金銭貸付は「長期貸付金」。'
  },
  {
    id: 182,
    question: "Equity investments in subsidiaries and associates are classified as (　).",
    translation: "子会社・関連会社への株式投資は（　）として分類される。",
    choices: ["Shares of subsidiaries and associates", "Investment securities", "Marketable securities"],
    meanings: ["関係会社株式", "投資有価証券", "有価証券"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産',
    explanation: '支配・影響力を持つ関係会社株式は「関係会社株式」。その他の長期保有株式は「投資有価証券」、短期売買目的は「有価証券」。'
  },
  {
    id: 183,
    question: "Membership rights in golf clubs and other recreational facilities are shown as (　).",
    translation: "ゴルフクラブその他娯楽施設の会員権は（　）として表示される。",
    choices: ["Membership rights", "Investment securities", "Intangible assets"],
    meanings: ["会員権", "投資有価証券", "無形固定資産"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産',
    explanation: 'ゴルフ会員権等は「会員権」（投資その他の資産）。株式・債券は「投資有価証券」、特許権等は「無形固定資産」。'
  },
  {
    id: 184,
    question: "Insurance policies with cash surrender value held by the company are recorded as (　).",
    translation: "会社が保有する解約返戻金のある保険契約は（　）として記録される。",
    choices: ["Insurance funds", "Investment securities", "Prepaid expenses"],
    meanings: ["保険積立金", "投資有価証券", "前払費用"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産',
    explanation: '解約返戻金のある生命保険等は「保険積立金」（投資その他の資産）。有価証券は別科目、保険料の前払いは「前払費用」。'
  },
  {
    id: 185,
    question: "The portion of bonds payable due within one year is reclassified as (　).",
    translation: "社債のうち1年以内に償還期限が到来する部分は（　）に振り替えられる。",
    choices: ["Current portion of bonds payable", "Bonds payable", "Short-term borrowings"],
    meanings: ["1年内償還予定の社債", "社債", "短期借入金"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '負債',
    explanation: '社債の1年以内償還分は流動負債の「1年内償還予定の社債」に振替。1年超分は「社債」、借入金は別科目。'
  },
  {
    id: 186,
    question: "Asset retirement obligations for the future removal or restoration costs of assets are recorded as (　).",
    translation: "資産の将来の除去または原状回復費用に係る債務は（　）として記録される。",
    choices: ["Asset retirement obligations", "Provision for product warranties", "Accrued expenses"],
    meanings: ["資産除去債務", "製品保証引当金", "未払費用"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '負債',
    explanation: '有形固定資産の除去・原状回復義務は「資産除去債務」（取得時に計上）。製品保証は別科目、通常の未払いは「未払費用」。'
  },
  {
    id: 187,
    question: "Proceeds from issuing shares in excess of par value are recorded in (　).",
    translation: "額面を超えて株式を発行した際の払込額は（　）に記録される。",
    choices: ["Share capital and capital surplus", "Retained earnings", "Treasury shares"],
    meanings: ["資本金及び資本剰余金", "利益剰余金", "自己株式"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '純資産',
    explanation: '株式発行による払込額は「資本金」と「資本剰余金」に配分（会社法）。稼得利益は「利益剰余金」、自己株式は純資産のマイナス。'
  },
  {
    id: 188,
    question: "Unrealized gains or losses on available-for-sale securities are shown in (　).",
    translation: "その他有価証券の未実現損益は（　）に表示される。",
    choices: ["Valuation difference on available-for-sale securities", "Retained earnings", "Non-operating income"],
    meanings: ["その他有価証券評価差額金", "利益剰余金", "営業外収益"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '純資産',
    explanation: 'その他有価証券の時価評価差額は「その他有価証券評価差額金」（純資産の部）。実現時に損益計算書へ。'
  },
  {
    id: 189,
    question: "Foreign currency translation adjustments for foreign operations are accumulated in (　).",
    translation: "在外営業活動体の外貨換算調整額は（　）に累積される。",
    choices: ["Foreign currency translation adjustments", "Foreign exchange gains", "Retained earnings"],
    meanings: ["為替換算調整勘定", "為替差益", "利益剰余金"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '純資産',
    explanation: '在外子会社等の換算差額は「為替換算調整勘定」（純資産の部）。通常の為替差損益は損益計算書、利益剰余金は稼得利益。'
  },
  {
    id: 190,
    question: "Amounts set aside from profits for specific future purposes are classified as (　).",
    translation: "特定の将来目的のために利益から積み立てた金額は（　）として分類される。",
    choices: ["Voluntary reserves", "Legal reserve", "Retained earnings brought forward"],
    meanings: ["任意積立金", "利益準備金", "繰越利益剰余金"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '純資産',
    explanation: '任意で積み立てる準備金は「任意積立金」（別途積立金、圧縮積立金等）。法定の積立ては「利益準備金」、未処分は「繰越利益剰余金」。'
  },
  {
    id: 191,
    question: "Undistributed profits carried forward from previous periods are shown as (　).",
    translation: "前期から繰り越された未分配利益は（　）として表示される。",
    choices: ["Retained earnings brought forward", "Legal reserve", "Voluntary reserves"],
    meanings: ["繰越利益剰余金", "利益準備金", "任意積立金"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '純資産',
    explanation: '処分されていない利益の累積は「繰越利益剰余金」。法定積立ては「利益準備金」、任意積立ては「任意積立金」。'
  },
  {
    id: 160,
    question: "The excess of plan assets over retirement benefit obligations is recorded as (　).",
    translation: "退職給付債務を年金資産が上回る部分は（　）として記録される。",
    choices: ["Prepaid pension costs", "Retirement benefit liability", "Retirement benefit expenses"],
    meanings: ["前払年金費用", "退職給付に係る負債", "退職給付費用"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産',
    explanation: '年金資産＞退職給付債務の場合は「前払年金費用」（資産）。逆の場合は「退職給付に係る負債」、当期費用は「退職給付費用」。'
  },
  {
    id: 161,
    question: "Revenue from providing services rather than selling goods is recorded as (　).",
    translation: "商品販売ではなくサービス提供による収益は（　）として記録される。",
    choices: ["Service revenue or operating revenue", "Net sales", "Interest income"],
    meanings: ["役務収益または営業収益", "売上高", "受取利息"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '収益',
    explanation: 'サービス業の主要収益は「役務収益」または「営業収益」。商品販売は「売上高」、利息収入は「受取利息」。'
  },
  {
    id: 162,
    question: "Rental income from leasing property to others is shown as (　).",
    translation: "他者への不動産賃貸による収入は（　）として表示される。",
    choices: ["Rental income", "Net sales", "Interest income"],
    meanings: ["賃貸料収入", "売上高", "受取利息"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '収益',
    explanation: '不動産賃貸収入は「賃貸料収入」（営業外収益または売上高）。商品販売は「売上高」、利息は「受取利息」。'
  },
  {
    id: 163,
    question: "Royalties received from licensing intellectual property are recorded as (　).",
    translation: "知的財産のライセンスから受け取るロイヤリティは（　）として記録される。",
    choices: ["Royalty income", "Net sales", "Dividend income"],
    meanings: ["ロイヤリティ収入", "売上高", "受取配当金"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '収益',
    explanation: '特許権・商標権等の使用料収入は「ロイヤリティ収入」（営業外収益）。商品販売は「売上高」、株式配当は「受取配当金」。'
  },
  {
    id: 164,
    question: "Income from insurance claims received for damages or losses is shown as (　).",
    translation: "損害または損失に対して受け取った保険金収入は（　）として表示される。",
    choices: ["Insurance claim income", "Gain on sale of property, plant and equipment", "Non-operating income"],
    meanings: ["保険金収入", "固定資産売却益", "営業外収益"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '収益',
    explanation: '火災・災害等の保険金は「保険金収入」（特別利益）。固定資産売却益は別科目、一般的な営業外収益も区分。'
  },
  {
    id: 165,
    question: "An (　) is a formal agreement between the auditor and the client that defines the scope, responsibilities, and terms of the audit.",
    translation: "（　）とは、監査の範囲、責任、条件を定める監査人と依頼人の間の正式な合意である。",
    choices: ["Audit engagement", "Audit plan", "Audit evidence"],
    meanings: ["監査契約", "監査計画", "監査証拠"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '基本概念',
    explanation: '監査契約(Audit engagement)は監査業務の基礎となる契約。監査計画は監査の実施方針、監査証拠は監査意見の基礎となる情報を指す。'
  },
  {
    id: 166,
    question: "(　) refers to the auditor's freedom from relationships that could impair objective professional judgment.",
    translation: "（　）とは、客観的な職業的判断を損なう可能性のある関係からの自由を指す。",
    choices: ["Independence", "Competence", "Due care"],
    meanings: ["独立性", "専門的能力", "正当な注意"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '基本概念',
    explanation: '独立性(Independence)は公認会計士法で要求される基本原則。専門的能力は技術や知識、正当な注意は慎重さと懐疑心を指す。'
  },
  {
    id: 167,
    question: "Under the Certified Public Accountants Act, auditors are prohibited from having (　) with their audit clients, such as financial interests or close personal relationships.",
    translation: "公認会計士法により、監査人は監査依頼人との（　）、例えば財務的利害や親密な個人的関係を持つことが禁止されている。",
    choices: ["Conflict of interest", "Communication", "Consultation"],
    meanings: ["利害関係", "コミュニケーション", "相談"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '基本概念',
    explanation: '公認会計士法第24条の2で利害関係(Conflict of interest)が禁止されている。依頼人とのコミュニケーションや相談は適切に行うべきもの。'
  },
  {
    id: 168,
    question: "(　) is the professional duty that requires auditors to protect client information from unauthorized disclosure.",
    translation: "（　）とは、監査人が依頼人の情報を無断開示から保護することを要求する職業上の義務である。",
    choices: ["Confidentiality", "Integrity", "Objectivity"],
    meanings: ["守秘義務", "誠実性", "客観性"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '基本概念',
    explanation: '守秘義務(Confidentiality)は公認会計士法第27条で規定。誠実性は正直さ、客観性は偏見を持たないことを指す。'
  },
  {
    id: 169,
    question: "(　) is the system established by an audit firm to provide reasonable assurance that the firm and its personnel comply with professional standards.",
    translation: "（　）とは、監査法人とその職員が職業的基準に準拠していることの合理的保証を提供するために監査法人が確立するシステムである。",
    choices: ["Quality control", "Risk assessment", "Internal control"],
    meanings: ["品質管理", "リスク評価", "内部統制"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '基本概念',
    explanation: '品質管理(Quality control)は監査基準委員会報告書第1号で要求される。リスク評価は監査手続の一部、内部統制は会社側のシステム。'
  },
  {
    id: 170,
    question: "An (　) is a professional entity established by five or more certified public accountants to perform statutory audits in Japan.",
    translation: "（　）とは、日本で法定監査を実施するために5名以上の公認会計士により設立される専門組織である。",
    choices: ["Audit firm", "Accounting firm", "Audit committee"],
    meanings: ["監査法人", "会計事務所", "監査委員会"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '基本概念',
    explanation: '監査法人(Audit firm)は公認会計士法第34条の2で規定。会計事務所は税務等も行う、監査委員会は会社側の機関。'
  },
  {
    id: 171,
    question: "The (　) is the partner in an audit firm who has overall responsibility for the audit engagement and the audit report issued.",
    translation: "（　）とは、監査業務全体と発行される監査報告書に対して全体的な責任を負う監査法人のパートナーである。",
    choices: ["Engagement partner", "Audit manager", "Quality control reviewer"],
    meanings: ["業務執行社員", "監査マネージャー", "品質管理レビュー担当者"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '基本概念',
    explanation: '業務執行社員(Engagement partner)が最終責任を負う。監査マネージャーは補助的役割、品質管理レビュー担当者は独立的な審査を行う。'
  },
  {
    id: 172,
    question: "The (　) includes all professionals performing the audit, from partners to staff auditors.",
    translation: "（　）には、パートナーからスタッフ監査人まで、監査を実施する全ての専門家が含まれる。",
    choices: ["Engagement team", "Management team", "Governance structure"],
    meanings: ["監査チーム", "経営チーム", "ガバナンス体制"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '基本概念',
    explanation: '監査チーム(Engagement team)は監査を実施する監査法人側の人員。経営チームとガバナンス体制は会社側の組織。'
  },
  {
    id: 173,
    question: "The (　) of a financial statement audit is to express an opinion on whether the financial statements are presented fairly in accordance with the applicable financial reporting framework.",
    translation: "財務諸表監査の（　）は、財務諸表が適用される財務報告の枠組みに準拠して適正に表示されているかについて意見を表明することである。",
    choices: ["Objective", "Procedure", "Scope"],
    meanings: ["目的", "手続", "範囲"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '基本概念',
    explanation: '監査の目的(Objective)は監査基準で明確に規定。手続は目的達成の方法、範囲は監査の対象領域を指す。'
  },
  {
    id: 174,
    question: "(　) is a high level of assurance obtained when the auditor has gathered sufficient appropriate audit evidence, but it is not an absolute guarantee.",
    translation: "（　）とは、監査人が十分かつ適切な監査証拠を収集した場合に得られる高い水準の保証であるが、絶対的な保証ではない。",
    choices: ["Reasonable assurance", "Limited assurance", "Negative assurance"],
    meanings: ["合理的保証", "限定的保証", "消極的保証"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '基本概念',
    explanation: '合理的保証(Reasonable assurance)は財務諸表監査で提供される保証水準。限定的保証はレビュー業務、消極的保証は「重要な虚偽表示は認められなかった」という表現。'
  },
  {
    id: 175,
    question: "(　) cannot be achieved in an audit due to inherent limitations such as the use of sampling and the possibility of management override.",
    translation: "（　）は、サンプリングの使用や経営者による無効化の可能性などの固有の限界により、監査では達成できない。",
    choices: ["Absolute assurance", "Reasonable assurance", "Professional skepticism"],
    meanings: ["絶対的保証", "合理的保証", "職業的懐疑心"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '基本概念',
    explanation: '絶対的保証(Absolute assurance)は監査では提供不可能。合理的保証が監査の保証水準、職業的懐疑心は監査人の姿勢。'
  },
  {
    id: 176,
    question: "(　) are unavoidable constraints on the auditor's ability to detect all material misstatements, such as the use of testing and the persuasive nature of evidence.",
    translation: "（　）とは、試査の使用や証拠の説得力という性質など、全ての重要な虚偽表示を発見する監査人の能力における避けられない制約である。",
    choices: ["Inherent limitations", "Scope limitations", "Detection risks"],
    meanings: ["固有の限界", "範囲の制約", "発見リスク"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '基本概念',
    explanation: '固有の限界(Inherent limitations)は監査手法上避けられない制約。範囲の制約は依頼人による制限、発見リスクは監査手続が虚偽表示を発見できないリスク。'
  },
  {
    id: 177,
    question: "(　) are authoritative guidelines established by the Business Accounting Council that govern the conduct of audits in Japan.",
    translation: "（　）とは、企業会計審議会により設定された、日本における監査の実施を規定する権威ある指針である。",
    choices: ["Auditing standards", "Accounting standards", "Internal control standards"],
    meanings: ["監査基準", "会計基準", "内部統制基準"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '基本概念',
    explanation: '監査基準(Auditing standards)は監査の実施基準。会計基準は財務諸表作成の基準、内部統制基準は内部統制の構築・評価基準。'
  },
  {
    id: 178,
    question: "(　) is the information used by the auditor to support the conclusions on which the audit opinion is based.",
    translation: "（　）とは、監査意見の基礎となる結論を裏付けるために監査人が使用する情報である。",
    choices: ["Audit evidence", "Audit documentation", "Audit report"],
    meanings: ["監査証拠", "監査調書", "監査報告書"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '基本概念',
    explanation: '監査証拠(Audit evidence)は監査意見の基礎。監査調書は監査証拠を記録した文書、監査報告書は意見を表明する文書。'
  },
  {
    id: 179,
    question: "(　) is the magnitude of misstatements that could reasonably influence the economic decisions of users based on the financial statements.",
    translation: "（　）とは、財務諸表に基づく利用者の経済的意思決定に合理的に影響を与える可能性のある虚偽表示の大きさである。",
    choices: ["Materiality", "Significance", "Relevance"],
    meanings: ["重要性", "有意性", "関連性"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '基本概念',
    explanation: '重要性(Materiality)は監査における重要な判断基準で、監査計画や評価で使用。有意性は統計用語、関連性は情報の適切性を指す。'
  },
  {
    id: 180,
    question: "(　) is the risk that the auditor expresses an inappropriate audit opinion when the financial statements are materially misstated.",
    translation: "（　）とは、財務諸表に重要な虚偽表示がある場合に、監査人が不適切な監査意見を表明するリスクである。",
    choices: ["Audit risk", "Business risk", "Inherent risk"],
    meanings: ["監査リスク", "事業リスク", "固有リスク"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '基本概念',
    explanation: '監査リスク(Audit risk)は固有リスク×統制リスク×発見リスクで構成。事業リスクは会社の経営リスク、固有リスクは監査リスクの一要素。'
  },
  {
    id: 181,
    question: "(　) is the attitude of the auditor that includes a questioning mind and critical assessment of audit evidence.",
    translation: "（　）とは、質問する姿勢と監査証拠の批判的な評価を含む監査人の態度である。",
    choices: ["Professional skepticism", "Professional judgment", "Professional competence"],
    meanings: ["職業的懐疑心", "職業的判断", "職業的専門能力"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '基本概念',
    explanation: '職業的懐疑心(Professional skepticism)は監査基準で要求される基本的姿勢。職業的判断は結論を導く能力、職業的専門能力は技術と知識。'
  },
  {
    id: 182,
    question: "(　) is a process designed and implemented by management to provide reasonable assurance regarding the achievement of objectives relating to financial reporting.",
    translation: "（　）とは、財務報告に関する目的の達成について合理的保証を提供するために経営者により設計・実施されるプロセスである。",
    choices: ["Internal control", "External audit", "Risk management"],
    meanings: ["内部統制", "外部監査", "リスク管理"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '基本概念',
    explanation: '内部統制(Internal control)は会社側が構築するシステム。外部監査は独立した監査人による監査、リスク管理は広範なリスク対応活動。'
  },
  {
    id: 183,
    question: "The (　) is a formal document in which the auditor expresses an opinion on the financial statements.",
    translation: "（　）とは、監査人が財務諸表に対する意見を表明する正式な文書である。",
    choices: ["Audit report", "Management letter", "Engagement letter"],
    meanings: ["監査報告書", "経営者への書簡", "契約書"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '基本概念',
    explanation: '監査報告書(Audit report)は監査意見を表明する最終成果物。経営者への書簡は改善提案、契約書は監査契約を文書化したもの。'
  },
  {
    id: 184,
    question: "(　) is the assumption that an entity will continue in operation for the foreseeable future.",
    translation: "（　）とは、企業が予見可能な将来にわたり事業を継続するという前提である。",
    choices: ["Going concern", "Business continuity", "Sustainability"],
    meanings: ["継続企業の前提", "事業継続性", "持続可能性"],
    answer: 0,
    category: '監査論',
    source: 'user-provided list',
    subcategory: '基本概念',
    explanation: '継続企業の前提(Going concern)は財務諸表作成の基本前提で、監査人は評価義務がある。事業継続性は災害対応、持続可能性は環境・社会面を含む概念。'
  },
  {
    id: 121,
    question: "The assumption that an entity will continue its operations for the foreseeable future is called (　).",
    translation: "企業が予見可能な将来にわたり事業を継続するという前提を（　）と呼ぶ。",
    choices: ["Going concern assumption", "Accrual basis of accounting", "Matching principle"],
    meanings: ["継続企業の前提", "発生主義会計", "費用収益対応の原則"],
    answer: 0,
    category: '監査実務',
    source: '監査基準報告書',
    subcategory: '監査実務',
    explanation: '報告書570で規定。企業が清算を前提とせず事業を継続することを前提に財務諸表を作成する考え方。'
  },
  {
    id: 122,
    question: "Monetary amounts in financial statements that are subject to measurement uncertainty and require management judgment are called (　).",
    translation: "測定の不確実性があり経営者の判断を要する財務諸表上の金額を（　）と呼ぶ。",
    choices: ["Accounting estimates", "Actual results", "Historical costs"],
    meanings: ["会計上の見積り", "実績値", "取得原価"],
    answer: 0,
    category: '監査実務',
    source: '監査基準報告書',
    subcategory: '監査実務',
    explanation: '報告書540で規定。貸倒引当金、減損損失等、直接観察できない金額を合理的に算出すること。'
  },
  {
    id: 123,
    question: "A misstatement that could influence the economic decisions of users based on the financial statements is called (　).",
    translation: "財務諸表に基づく利用者の経済的意思決定に影響を与える可能性のある虚偽表示を（　）と呼ぶ。",
    choices: ["Material misstatement", "Immaterial misstatement", "Clearly trivial misstatement"],
    meanings: ["重要な虚偽表示", "重要性のない虚偽表示", "明らかに僅少な虚偽表示"],
    answer: 0,
    category: '監査実務',
    source: '監査基準報告書',
    subcategory: '監査実務',
    explanation: '監査リスクの中心概念。重要性の基準値を超える虚偽表示。'
  },
  {
    id: 124,
    question: "A difference between a financial statement item and the amount required by the applicable financial reporting framework is called (　).",
    translation: "財務諸表項目と財務報告の枠組みで要求される金額との差異を（　）と呼ぶ。",
    choices: ["Misstatement", "Adjustment", "Reclassification"],
    meanings: ["虚偽表示", "修正仕訳", "組替"],
    answer: 0,
    category: '監査実務',
    source: '監査基準報告書',
    subcategory: '監査実務',
    explanation: '誤謬と不正の両方を含む概念。金額、分類、表示、開示の誤りを含む。'
  },
  {
    id: 125,
    question: "Misstatements that the auditor has accumulated and that have not been corrected are called (　).",
    translation: "監査人が集計し、修正されていない虚偽表示を（　）と呼ぶ。",
    choices: ["Uncorrected misstatements", "Adjusted misstatements", "Passed adjustments"],
    meanings: ["未修正虚偽表示", "修正済虚偽表示", "未計上修正事項"],
    answer: 0,
    category: '監査実務',
    source: '監査基準報告書',
    subcategory: '監査実務',
    explanation: '報告書450で規定。監査意見形成時に重要性を評価する対象。'
  },
  {
    id: 126,
    question: "Prior period financial information included for comparison with current period amounts is called (　).",
    translation: "当期の金額と比較するために含まれる前期の財務情報を（　）と呼ぶ。",
    choices: ["Comparative information", "Prior period adjustments", "Corresponding figures"],
    meanings: ["比較情報", "過年度修正", "対応数値"],
    answer: 0,
    category: '監査実務',
    source: '監査基準報告書',
    subcategory: '監査実務',
    explanation: '報告書710で規定。前期財務諸表を当期と並べて表示する方式。'
  },
  {
    id: 127,
    question: "Account balances that exist at the beginning of the current period are called (　).",
    translation: "当期の開始時点に存在する勘定残高を（　）と呼ぶ。",
    choices: ["Opening balances", "Closing balances", "Cumulative balances"],
    meanings: ["期首残高", "期末残高", "累積残高"],
    answer: 0,
    category: '監査実務',
    source: '監査基準報告書',
    subcategory: '監査実務',
    explanation: '報告書510で規定。初年度監査では特別な手続が必要。'
  },
  {
    id: 128,
    question: "Parties that control, are controlled by, or are under common control with the entity are called (　).",
    translation: "企業を支配、企業に支配される、または企業と共通の支配下にある当事者を（　）と呼ぶ。",
    choices: ["Related parties", "Third parties", "Independent parties"],
    meanings: ["関連当事者", "第三者", "独立当事者"],
    answer: 0,
    category: '監査実務',
    source: '監査基準報告書',
    subcategory: '監査実務',
    explanation: '報告書550で規定。親会社、子会社、主要株主、経営者等を含む。'
  },
  {
    id: 129,
    question: "Events occurring between the date of the financial statements and the date of the auditor's report are called (　).",
    translation: "財務諸表日から監査報告書日までの間に発生した事象を（　）と呼ぶ。",
    choices: ["Subsequent events", "Prior period events", "Adjusting events"],
    meanings: ["後発事象", "前期事象", "修正後発事象"],
    answer: 0,
    category: '監査実務',
    source: '監査基準報告書',
    subcategory: '監査実務',
    explanation: '報告書560で規定。修正後発事象と開示後発事象に区分。'
  },
  {
    id: 130,
    question: "A written statement provided by management to confirm certain matters is called (　).",
    translation: "特定事項を確認するため経営者が提供する書面を（　）と呼ぶ。",
    choices: ["Management representation letter", "Engagement letter", "Comfort letter"],
    meanings: ["経営者確認書", "監査契約書", "コンフォートレター"],
    answer: 0,
    category: '監査実務',
    source: '監査基準報告書',
    subcategory: '監査実務',
    explanation: '報告書580で入手が義務付け。経営者の責任や事実の確認を文書化。'
  },
  {
    id: 131,
    question: "Controls over the entity's use of information technology are called (　).",
    translation: "企業の情報技術の利用に関する統制を（　）と呼ぶ。",
    choices: ["IT controls", "Manual controls", "Detective controls"],
    meanings: ["IT統制", "手作業による統制", "発見的統制"],
    answer: 0,
    category: '監査実務',
    source: '監査基準報告書',
    subcategory: '監査実務',
    explanation: '全般統制と業務処理統制に区分。報告書315でリスク評価の対象。'
  },
  {
    id: 132,
    question: "IT controls that apply to all systems and support the effective functioning of application controls are called (　).",
    translation: "全システムに適用され業務処理統制の有効性を支援するIT統制を（　）と呼ぶ。",
    choices: ["General IT controls", "Application controls", "Access controls"],
    meanings: ["全般統制", "業務処理統制", "アクセス統制"],
    answer: 0,
    category: '監査実務',
    source: '監査基準報告書',
    subcategory: '監査実務',
    explanation: 'システム開発・保守、アクセス管理、変更管理等を含む。'
  },
  {
    id: 133,
    question: "IT controls built into individual application systems are called (　).",
    translation: "個別のアプリケーションシステムに組み込まれたIT統制を（　）と呼ぶ。",
    choices: ["Application controls", "General IT controls", "Input controls"],
    meanings: ["業務処理統制", "全般統制", "入力統制"],
    answer: 0,
    category: '監査実務',
    source: '監査基準報告書',
    subcategory: '監査実務',
    explanation: '入力、処理、出力の各段階での統制を含む。'
  },
  {
    id: 134,
    question: "A weakness in internal control exists when a control does not prevent or detect misstatements on a timely basis. This is called (　).",
    translation: "統制が虚偽表示を適時に防止または発見できない場合の内部統制の弱点を（　）と呼ぶ。",
    choices: ["Deficiency in internal control", "Significant deficiency", "Material weakness"],
    meanings: ["内部統制の不備", "重要な不備", "開示すべき重要な不備"],
    answer: 0,
    category: '監査実務',
    source: '監査基準報告書',
    subcategory: '監査実務',
    explanation: '報告書265で定義。程度により重要な不備、開示すべき重要な不備に区分。'
  },
  {
    id: 135,
    question: "Intentional misstatements in financial statements to deceive users is called (　).",
    translation: "利用者を欺くための財務諸表の意図的な虚偽表示を（　）と呼ぶ。",
    choices: ["Fraudulent financial reporting", "Error", "Misappropriation of assets"],
    meanings: ["不正な財務報告", "誤謬", "資産の流用"],
    answer: 0,
    category: '監査実務',
    source: '監査基準報告書',
    subcategory: '監査実務',
    explanation: '報告書240で規定。不正の一類型で、経営者による場合が多い。'
  },
  {
    id: 136,
    question: "Theft or misuse of an entity's assets is called (　).",
    translation: "企業資産の盗取または不正使用を（　）と呼ぶ。",
    choices: ["Misappropriation of assets", "Fraudulent financial reporting", "Embezzlement"],
    meanings: ["資産の流用", "不正な財務報告", "横領"],
    answer: 0,
    category: '監査実務',
    source: '監査基準報告書',
    subcategory: '監査実務',
    explanation: '報告書240で規定。不正のもう一つの類型。現金、棚卸資産等が対象。'
  },
  {
    id: 137,
    question: "Events or conditions that indicate incentives, pressures, or opportunities to commit fraud are called (　).",
    translation: "不正を行う動機、プレッシャー、または機会を示す事象や状況を（　）と呼ぶ。",
    choices: ["Fraud risk factors", "Fraud indicators", "Red flags"],
    meanings: ["不正リスク要因", "不正の兆候", "警告信号"],
    answer: 0,
    category: '監査実務',
    source: '監査基準報告書',
    subcategory: '監査実務',
    explanation: '報告書240で規定。不正のトライアングル（動機・機会・正当化）に対応。'
  },
  {
    id: 138,
    question: "Management's ability to override controls that otherwise operate effectively is called (　).",
    translation: "有効に運用されている統制を経営者が無効にする能力を（　）と呼ぶ。",
    choices: ["Management override of controls", "Control failure", "Control deviation"],
    meanings: ["経営者による内部統制の無効化", "統制の失敗", "統制の逸脱"],
    answer: 0,
    category: '監査実務',
    source: '監査基準報告書',
    subcategory: '監査実務',
    explanation: '報告書240で特別な対応が要求される重要な不正リスク。'
  },
  {
    id: 139,
    question: "An individual or organization possessing expertise in a field other than accounting or auditing, whose work is used by the auditor, is called (　).",
    translation: "会計・監査以外の分野の専門知識を有し、監査人が業務を利用する個人または組織を（　）と呼ぶ。",
    choices: ["Auditor's expert", "Management's expert", "Component auditor"],
    meanings: ["監査人の利用する専門家", "経営者の利用する専門家", "構成単位の監査人"],
    answer: 0,
    category: '監査実務',
    source: '監査基準報告書',
    subcategory: '監査実務',
    explanation: '報告書620で規定。不動産鑑定士、弁護士、アクチュアリー等。'
  },
  {
    id: 140,
    question: "The external auditor's use of work performed by internal auditors is called (　).",
    translation: "内部監査人が実施した作業を外部監査人が利用することを（　）と呼ぶ。",
    choices: ["Using the work of internal auditors", "Internal audit outsourcing", "Co-sourcing"],
    meanings: ["内部監査人の作業の利用", "内部監査の外部委託", "共同調達"],
    answer: 0,
    category: '監査実務',
    source: '監査基準報告書',
    subcategory: '監査実務',
    explanation: '報告書610で規定。内部監査の客観性と能力を評価後に利用可能。'
  },
  {
    id: 141,
    question: "An auditor who performs work on financial information of a component for a group audit is called (　).",
    translation: "グループ監査のために構成単位の財務情報に関する作業を実施する監査人を（　）と呼ぶ。",
    choices: ["Component auditor", "Group engagement partner", "Principal auditor"],
    meanings: ["構成単位の監査人", "グループ監査の業務執行社員", "主たる監査人"],
    answer: 0,
    category: '監査実務',
    source: '監査基準報告書',
    subcategory: '監査実務',
    explanation: '報告書600で規定。子会社等の個別監査を担当。'
  },
  {
    id: 142,
    question: "The audit of group financial statements is called (　).",
    translation: "グループ財務諸表の監査を（　）と呼ぶ。",
    choices: ["Group audit", "Consolidated audit", "Multi-location audit"],
    meanings: ["グループ監査", "連結監査", "多拠点監査"],
    answer: 0,
    category: '監査実務',
    source: '監査基準報告書',
    subcategory: '監査実務',
    explanation: '報告書600で規定。構成単位の財務情報を含む監査。'
  },
  {
    id: 143,
    question: "A component identified as financially significant to the group or likely to include significant risks is called (　).",
    translation: "グループにとって財務的に重要、または重要なリスクを含む可能性が高い構成単位を（　）と呼ぶ。",
    choices: ["Significant component", "Immaterial component", "Major subsidiary"],
    meanings: ["重要な構成単位", "重要性のない構成単位", "主要子会社"],
    answer: 0,
    category: '監査実務',
    source: '監査基準報告書',
    subcategory: '監査実務',
    explanation: '報告書600で定義。個別監査または特定項目の監査を実施。'
  },
  {
    id: 144,
    question: "Physical examination of assets by the auditor is called (　).",
    translation: "監査人による資産の物理的調査を（　）と呼ぶ。",
    choices: ["Inspection of tangible assets", "Observation", "Physical inventory count"],
    meanings: ["有形資産の実査", "立会", "実地棚卸"],
    answer: 0,
    category: '監査実務',
    source: '監査基準報告書',
    subcategory: '監査実務',
    explanation: '現金、有価証券、棚卸資産等を監査人自ら確認する手続。'
  },
  {
    id: 145,
    question: "Observing a process or procedure being performed by others is called (　).",
    translation: "他者により実施されるプロセスや手続を観察することを（　）と呼ぶ。",
    choices: ["Observation", "Inspection", "Inquiry"],
    meanings: ["立会", "実査・閲覧", "質問"],
    answer: 0,
    category: '監査実務',
    source: '監査基準報告書',
    subcategory: '監査実務',
    explanation: '報告書501で棚卸立会が要求される。内部統制の運用状況確認にも利用。'
  },
  {
    id: 146,
    question: "A direct written response from a third party to the auditor is called (　).",
    translation: "第三者から監査人への直接の書面による回答を（　）と呼ぶ。",
    choices: ["Confirmation", "Inquiry", "External evidence"],
    meanings: ["確認", "質問", "外部証拠"],
    answer: 0,
    category: '監査実務',
    source: '監査基準報告書',
    subcategory: '監査実務',
    explanation: '報告書505で規定。銀行、得意先、弁護士等への直接問い合わせ。'
  },
  {
    id: 147,
    question: "Examination of records or documents is called (　).",
    translation: "記録や文書の調査を（　）と呼ぶ。",
    choices: ["Inspection of records and documents", "Observation", "Reperformance"],
    meanings: ["記録や文書の閲覧", "立会", "再実施"],
    answer: 0,
    category: '監査実務',
    source: '監査基準報告書',
    subcategory: '監査実務',
    explanation: '契約書、議事録、請求書等の文書を調査する手続。'
  },
  {
    id: 148,
    question: "Checking the mathematical accuracy of documents or records is called (　).",
    translation: "文書または記録の計算の正確性を検証することを（　）と呼ぶ。",
    choices: ["Recalculation", "Reperformance", "Analytical procedures"],
    meanings: ["再計算", "再実施", "分析的手続"],
    answer: 0,
    category: '監査実務',
    source: '監査基準報告書',
    subcategory: '監査実務',
    explanation: '減価償却費、利息計算等の数値を独自に計算して検証。'
  },
  {
    id: 149,
    question: "The auditor's independent execution of procedures originally performed as internal control is called (　).",
    translation: "内部統制として実施された手続を監査人が独自に実行することを（　）と呼ぶ。",
    choices: ["Reperformance", "Recalculation", "Inspection"],
    meanings: ["再実施", "再計算", "閲覧"],
    answer: 0,
    category: '監査実務',
    source: '監査基準報告書',
    subcategory: '監査実務',
    explanation: '運用評価手続の一つ。請求書照合、承認手続等を独立的に実行。'
  },
  {
    id: 150,
    question: "Seeking information from knowledgeable persons is called (　).",
    translation: "知識を有する者から情報を求めることを（　）と呼ぶ。",
    choices: ["Inquiry", "Confirmation", "Interview"],
    meanings: ["質問", "確認", "面談"],
    answer: 0,
    category: '監査実務',
    source: '監査基準報告書',
    subcategory: '監査実務',
    explanation: '経営者、従業員、外部の弁護士等への口頭または書面による質問。'
  },
  {
    id: 151,
    question: "The auditor's conclusion about whether financial statements are prepared in accordance with the applicable framework is called (　).",
    translation: "財務諸表が適用される枠組みに準拠して作成されているかについての監査人の結論を（　）と呼ぶ。",
    choices: ["Audit opinion", "Audit conclusion", "Audit finding"],
    meanings: ["監査意見", "監査の結論", "監査発見事項"],
    answer: 0,
    category: '監査実務',
    source: '監査基準報告書',
    subcategory: '監査実務',
    explanation: '報告書700で規定。無限定、限定付、不適正、意見不表明に区分。'
  },
  {
    id: 152,
    question: "Matters that were of most significance in the audit of the current period, selected from matters communicated with those charged with governance, are called (　).",
    translation: "監査役等とコミュニケーションを行った事項から選択された、当年度の監査で最も重要であった事項を（　）と呼ぶ。",
    choices: ["Key audit matters", "Emphasis of matter", "Other matter"],
    meanings: ["監査上の主要な検討事項", "強調事項", "その他の事項"],
    answer: 0,
    category: '監査実務',
    source: '監査基準報告書',
    subcategory: '監査実務',
    explanation: '報告書701で規定。上場会社監査で記載が義務化（2021年3月期以降）。'
  }
];

module.exports = questions;