const questions = [
  {
    id: 1,
    question: "The company increased its (　), improving short-term liquidity.",
    translation: "会社は短期的な流動性を高めるために現金及び預金を増やした。",
    choices: ["Cash and deposits", "Short-term loans receivable", "Securities"],
    meanings: ["現金及び預金", "短期貸付金", "有価証券"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産'
  },
  {
    id: 2,
    question: "The company purchased (　) as a short-term investment.",
    translation: "会社は短期投資として有価証券を購入した。",
    choices: ["Securities", "Merchandise", "Accounts receivable - trade"],
    meanings: ["有価証券", "商品", "売掛金"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産'
  },
  {
    id: 3,
    question: "The company holds (　) as negotiable instruments awaiting payment.",
    translation: "会社は支払を待つための受取手形を保有している。",
    choices: ["Notes receivable - trade", "Accounts receivable - trade", "Accrued revenue"],
    meanings: ["受取手形", "売掛金", "未収収益"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産'
  },
  {
    id: 4,
    question: "Sales on credit are recorded as (　) until cash is received.",
    translation: "掛売上は回収されるまで売掛金として記録される。",
    choices: ["Accounts receivable - trade", "Advances received", "Securities"],
    meanings: ["売掛金", "前受金", "有価証券"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産'
  },
  {
    id: 5,
    question: "Interest earned but not yet received is recognized as (　).",
    translation: "未受取の利息は未収収益として認識される。",
    choices: ["Accrued revenue", "Interest income", "Accounts receivable - other"],
    meanings: ["未収収益", "受取利息", "未収入金"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産'
  },
  {
    id: 6,
    question: "Materials held for production are reported as (　).",
    translation: "生産用に保有している原材料として報告される。",
    choices: ["Raw materials", "Finished goods", "Work in process"],
    meanings: ["原材料", "製品", "仕掛品"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産'
  },
  {
    id: 7,
    question: "Buildings used in operations are classified as (　).",
    translation: "営業に使用される建物は有形固定資産に分類される。",
    choices: ["Property, plant and equipment", "Intangible assets", "Current assets"],
    meanings: ["有形固定資産", "無形固定資産", "流動資産"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産'
  },
  {
    id: 8,
    question: "Patent rights owned by the company are recorded as (　).",
    translation: "会社が所有する特許権は無形固定資産として記録される。",
    choices: ["Intangible assets", "Property, plant and equipment", "Current assets"],
    meanings: ["無形固定資産", "有形固定資産", "流動資産"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産'
  },
  {
    id: 9,
    question: "Goodwill from a business acquisition is recorded as (　).",
    translation: "事業買収から生じたのれんとして記録される。",
    choices: ["Goodwill", "Intangible assets", "Investment securities"],
    meanings: ["のれん", "無形固定資産", "投資有価証券"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産'
  },
  {
    id: 10,
    question: "Software developed for internal use is classified as (　).",
    translation: "内部使用目的で開発されたソフトウエアとして分類される。",
    choices: ["Software", "Intangible assets", "Supplies"],
    meanings: ["ソフトウエア", "無形固定資産", "貯蔵品"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産'
  },
  {
    id: 11,
    question: "Goods purchased on credit are recorded as (　).",
    translation: "クレジットで購入した商品は買掛金として記録される。",
    choices: ["Accounts payable - trade", "Notes payable - trade", "Accrued expenses"],
    meanings: ["買掛金", "支払手形", "未払費用"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '負債'
  },
  {
    id: 12,
    question: "Salaries earned by employees but not yet paid are recorded as (　).",
    translation: "従業員が稼得したがまだ支払われていない給与は未払費用として記録される。",
    choices: ["Accrued expenses", "Accounts payable - other", "Advances received"],
    meanings: ["未払費用", "未払金", "前受金"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '負債'
  },
  {
    id: 13,
    question: "Income received in advance from customers is recorded as (　).",
    translation: "顧客から前払いされた収入は前受金として記録される。",
    choices: ["Advances received", "Deposits received", "Accrued expenses"],
    meanings: ["前受金", "預り金", "未払費用"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '負債'
  },
  {
    id: 14,
    question: "Bonds issued by the company are recorded as (　).",
    translation: "会社が発行した債券は社債として記録される。",
    choices: ["Bonds payable", "Long-term borrowings", "Short-term borrowings"],
    meanings: ["社債", "長期借入金", "短期借入金"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '負債'
  },
  {
    id: 15,
    question: "Completed products ready for sale are classified as (　).",
    translation: "販売可能な完成品は製品として分類される。",
    choices: ["Finished goods", "Work in process", "Raw materials"],
    meanings: ["製品", "仕掛品", "原材料"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産'
  },
  {
    id: 16,
    question: "The company recorded (　) for anticipated customer defaults.",
    translation: "会社は予想される顧客の債務不履行に対して貸倒引当金を計上した。",
    choices: ["Allowance for doubtful accounts", "Bad debt expenses", "Provision for bonuses"],
    meanings: ["貸倒引当金", "貸倒損失", "賞与引当金"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産'
  },
  {
    id: 17,
    question: "Payment obligations to suppliers are shown as (　).",
    translation: "仕入先への支払義務は買掛金として示される。",
    choices: ["Accounts payable - trade", "Accrued expenses", "Advances received"],
    meanings: ["買掛金", "未払費用", "前受金"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '負債'
  },
  {
    id: 18,
    question: "The firm issued promissory notes recorded as (　).",
    translation: "会社は約束手形を発行し、支払手形として記録した。",
    choices: ["Notes payable - trade", "Accounts payable - trade", "Short-term borrowings"],
    meanings: ["支払手形", "買掛金", "短期借入金"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '負債'
  },
  {
    id: 19,
    question: "The company owns (　) for its operations.",
    translation: "会社は業務用の建物を所有している。",
    choices: ["Buildings", "Structures", "Land"],
    meanings: ["建物", "構築物", "土地"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産'
  },
  {
    id: 20,
    question: "Manufacturing equipment is classified as (　).",
    translation: "製造設備は機械装置として分類される。",
    choices: ["Machinery and equipment", "Tools, furniture and fixtures", "Vehicles"],
    meanings: ["機械装置", "工具器具備品", "車両運搬具"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産'
  },
  {
    id: 21,
    question: "The company owns property recorded as (　).",
    translation: "会社は土地として記録された不動産を所有している。",
    choices: ["Land", "Buildings", "Structures"],
    meanings: ["土地", "建物", "構築物"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産'
  },
  {
    id: 22,
    question: "Ongoing construction projects appear as (　) until completion.",
    translation: "進行中の建設プロジェクトは完成するまで建設仮勘定として計上される。",
    choices: ["Construction in progress", "Buildings", "Structures"],
    meanings: ["建設仮勘定", "建物", "構築物"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産'
  },
  {
    id: 23,
    question: "The cumulative depreciation is shown as (　).",
    translation: "累積減価償却額は減価償却累計額として示される。",
    choices: ["Accumulated depreciation", "Depreciation", "Impairment losses"],
    meanings: ["減価償却累計額", "減価償却費", "減損損失"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産'
  },
  {
    id: 24,
    question: "Computer programs are capitalized as (　).",
    translation: "コンピュータプログラムはソフトウエアとして資産計上される。",
    choices: ["Software", "Intangible assets", "Supplies"],
    meanings: ["ソフトウエア", "無形固定資産", "貯蔵品"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産'
  },
  {
    id: 25,
    question: "Acquisition premiums from business combinations are recognized as (　).",
    translation: "企業結合による取得プレミアムはのれんとして認識される。",
    choices: ["Goodwill", "Intangible assets", "Investment securities"],
    meanings: ["のれん", "無形固定資産", "投資有価証券"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産'
  },
  {
    id: 26,
    question: "Trademark rights are recorded as (　) on the balance sheet.",
    translation: "商標権は貸借対照表上、商標権として記録される。",
    choices: ["Trademark right", "Patent right", "Goodwill"],
    meanings: ["商標権", "特許権", "のれん"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産'
  },
  {
    id: 27,
    question: "Exclusive rights to inventions are shown as (　).",
    translation: "発明の独占権は特許権として示される。",
    choices: ["Patent right", "Trademark right", "Software"],
    meanings: ["特許権", "商標権", "ソフトウエア"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産'
  },
  {
    id: 28,
    question: "Expenses incurred but not yet paid are recorded as (　).",
    translation: "発生したが未払いの費用は未払費用として記録される。",
    choices: ["Accrued expenses", "Prepaid expenses", "Accounts payable - trade"],
    meanings: ["未払費用", "前払費用", "買掛金"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '負債'
  },
  {
    id: 29,
    question: "Amounts paid in advance are classified as (　).",
    translation: "前払金額は前払費用として分類される。",
    choices: ["Prepaid expenses", "Accrued expenses", "Advances received"],
    meanings: ["前払費用", "未払費用", "前受金"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '資産'
  },
  {
    id: 30,
    question: "Customer deposits received in advance are shown as (　).",
    translation: "顧客から事前に受け取った預り金は前受金として示される。",
    choices: ["Advances received", "Deposits received", "Accrued expenses"],
    meanings: ["前受金", "預り金", "未払費用"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '負債'
  },
  {
    id: 31,
    question: "Temporary amounts held on behalf of others are recorded as (　).",
    translation: "他者のために一時的に保管する金額は預り金として記録される。",
    choices: ["Deposits received", "Advances received", "Accrued expenses"],
    meanings: ["預り金", "前受金", "未払費用"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '負債'
  },
  {
    id: 32,
    question: "Long-term debt obligations are classified as (　).",
    translation: "長期債務は長期借入金として分類される。",
    choices: ["Long-term borrowings", "Short-term borrowings", "Bonds payable"],
    meanings: ["長期借入金", "短期借入金", "社債"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '負債'
  },
  {
    id: 33,
    question: "Corporate bonds issued are recorded as (　).",
    translation: "発行された社債は社債として記録される。",
    choices: ["Bonds payable", "Long-term borrowings", "Notes payable - trade"],
    meanings: ["社債", "長期借入金", "支払手形"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '負債'
  },
  {
    id: 34,
    question: "Expected employee bonus payments are shown as (　).",
    translation: "従業員への予想賞与支払額は賞与引当金として示される。",
    choices: ["Provision for bonuses", "Accrued expenses", "Bonuses"],
    meanings: ["賞与引当金", "未払費用", "賞与"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '負債'
  },
  {
    id: 35,
    question: "Liabilities for employee pensions are recorded as (　).",
    translation: "従業員の年金に対する負債は退職給付に係る負債として記録される。",
    choices: ["Retirement benefit liability", "Provision for retirement benefits", "Accrued expenses"],
    meanings: ["退職給付に係る負債", "退職給付引当金", "未払費用"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '負債'
  },
  {
    id: 36,
    question: "Temporary amounts held on behalf of third parties are shown as (　).",
    translation: "第三者のために一時的に保管する金額は預り金として示される。",
    choices: ["Deposits received", "Advances received", "Accounts payable - other"],
    meanings: ["預り金", "前受金", "未払金"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '負債'
  },
  {
    id: 37,
    question: "Corporate income tax obligations are shown as (　).",
    translation: "法人所得税の債務は未払法人税等として示される。",
    choices: ["Income taxes payable", "Accrued consumption taxes", "Accrued expenses"],
    meanings: ["未払法人税等", "未払消費税等", "未払費用"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '負債'
  },
  {
    id: 38,
    question: "The company's (　) increased by 15% compared to the previous year.",
    translation: "会社の売上高は前年比15%増加した。",
    choices: ["Net sales", "Operating revenue", "Interest income"],
    meanings: ["売上高", "営業収益", "受取利息"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '収益'
  },
  {
    id: 39,
    question: "Direct costs of goods sold are shown as (　).",
    translation: "販売された商品の直接原価は売上原価として示される。",
    choices: ["Cost of sales", "Selling, general and administrative expenses", "Depreciation"],
    meanings: ["売上原価", "販売費及び一般管理費", "減価償却費"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用'
  },
  {
    id: 40,
    question: "Annual depreciation charges are recorded as (　).",
    translation: "年間減価償却費は減価償却費として記録される。",
    choices: ["Depreciation", "Accumulated depreciation", "Impairment losses"],
    meanings: ["減価償却費", "減価償却累計額", "減損損失"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用'
  },
  {
    id: 41,
    question: "Costs paid to lenders for borrowing money are recorded as (　).",
    translation: "借入金に対して貸し手に支払う費用は支払利息として記録される。",
    choices: ["Interest expenses", "Commission expenses", "Insurance expenses"],
    meanings: ["支払利息", "支払手数料", "保険料"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用'
  },
  {
    id: 42,
    question: "Earnings from lending money or deposits are shown as (　).",
    translation: "貸付金や預金からの収益は受取利息として示される。",
    choices: ["Interest income", "Dividend income", "Operating revenue"],
    meanings: ["受取利息", "受取配当金", "営業収益"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '収益'
  },
  {
    id: 43,
    question: "Distributions to shareholders from profits are recorded as (　).",
    translation: "利益から株主への配当は受取配当金として記録される。",
    choices: ["Dividend income", "Interest income", "Operating revenue"],
    meanings: ["受取配当金", "受取利息", "営業収益"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '収益'
  },
  {
    id: 44,
    question: "Gains from favorable currency movements are shown as (　).",
    translation: "有利な為替変動による利益は為替差益として示される。",
    choices: ["Foreign exchange gains", "Interest income", "Gain on sale of non-current assets"],
    meanings: ["為替差益", "受取利息", "固定資産売却益"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '収益'
  },
  {
    id: 45,
    question: "Losses from unfavorable currency movements are recorded as (　).",
    translation: "不利な為替変動による損失は為替差損として記録される。",
    choices: ["Foreign exchange losses", "Interest expenses", "Loss on sale of non-current assets"],
    meanings: ["為替差損", "支払利息", "固定資産売却損"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用'
  },
  {
    id: 46,
    question: "Profits from selling fixed assets are shown as (　).",
    translation: "固定資産の売却による利益は固定資産売却益として示される。",
    choices: ["Gain on sale of non-current assets", "Interest income", "Foreign exchange gains"],
    meanings: ["固定資産売却益", "受取利息", "為替差益"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '収益'
  },
  {
    id: 47,
    question: "Losses from disposing of fixed assets are recorded as (　).",
    translation: "固定資産の処分による損失は固定資産売却損として記録される。",
    choices: ["Loss on sale of non-current assets", "Loss on retirement of non-current assets", "Impairment losses"],
    meanings: ["固定資産売却損", "固定資産除却損", "減損損失"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用'
  },
  {
    id: 48,
    question: "Asset value reductions due to impairment are shown as (　).",
    translation: "減損による資産価値の減少は減損損失として示される。",
    choices: ["Impairment losses", "Depreciation", "Loss on retirement of non-current assets"],
    meanings: ["減損損失", "減価償却費", "固定資産除却損"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用'
  },
  {
    id: 49,
    question: "Employee salaries and wages are recorded as (　).",
    translation: "従業員の給与と賃金は給料として記録される。",
    choices: ["Salaries", "Bonuses", "Welfare expenses"],
    meanings: ["給料", "賞与", "福利厚生費"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用'
  },
  {
    id: 50,
    question: "Employee benefits including insurance are shown as (　).",
    translation: "保険を含む従業員給付は福利厚生費として示される。",
    choices: ["Welfare expenses", "Legal welfare expenses", "Salaries"],
    meanings: ["福利厚生費", "法定福利費", "給料"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用'
  },
  {
    id: 51,
    question: "Costs for business travel are recorded as (　).",
    translation: "出張費用は旅費交通費として記録される。",
    choices: ["Travel and transportation expenses", "Communication expenses", "Meeting expenses"],
    meanings: ["旅費交通費", "通信費", "会議費"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用'
  },
  {
    id: 52,
    question: "Costs for phone, internet and mail are shown as (　).",
    translation: "電話、インターネット、郵便の費用は通信費として示される。",
    choices: ["Communication expenses", "Utilities", "Miscellaneous expenses"],
    meanings: ["通信費", "水道光熱費", "雑費"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用'
  },
  {
    id: 53,
    question: "Electricity, gas and water costs are recorded as (　).",
    translation: "電気、ガス、水道の費用は水道光熱費として記録される。",
    choices: ["Utilities", "Communication expenses", "Rent expenses"],
    meanings: ["水道光熱費", "通信費", "地代家賃"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用'
  },
  {
    id: 54,
    question: "Promotional and marketing costs are shown as (　).",
    translation: "販促及びマーケティング費用は広告宣伝費として示される。",
    choices: ["Advertising expenses", "Entertainment expenses", "Commission expenses"],
    meanings: ["広告宣伝費", "接待交際費", "支払手数料"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用'
  },
  {
    id: 55,
    question: "Business entertainment and hospitality costs are recorded as (　).",
    translation: "接待及び交際費用は接待交際費として記録される。",
    choices: ["Entertainment expenses", "Advertising expenses", "Meeting expenses"],
    meanings: ["接待交際費", "広告宣伝費", "会議費"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用'
  },
  {
    id: 56,
    question: "Property taxes and business license fees are shown as (　).",
    translation: "固定資産税及び営業許可料は租税公課として示される。",
    choices: ["Taxes and dues", "Insurance expenses", "Commission expenses"],
    meanings: ["租税公課", "保険料", "支払手数料"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用'
  },
  {
    id: 57,
    question: "Amounts paid for property and casualty coverage are recorded as (　).",
    translation: "財産及び損害保険のために支払った金額は保険料として記録される。",
    choices: ["Insurance expenses", "Taxes and dues", "Repair expenses"],
    meanings: ["保険料", "租税公課", "修繕費"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用'
  },
  {
    id: 58,
    question: "Costs for maintaining and repairing assets are shown as (　).",
    translation: "資産の維持及び修繕費用は修繕費として示される。",
    choices: ["Repair expenses", "Depreciation", "Utilities"],
    meanings: ["修繕費", "減価償却費", "水道光熱費"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用'
  },
  {
    id: 59,
    question: "Office supplies and consumables are recorded as (　).",
    translation: "事務用品及び消耗品は消耗品費として記録される。",
    choices: ["Supplies expenses", "Miscellaneous expenses", "Supplies"],
    meanings: ["消耗品費", "雑費", "貯蔵品"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用'
  },
  {
    id: 60,
    question: "Rent payments for buildings and land are shown as (　).",
    translation: "建物及び土地の賃借料は地代家賃として示される。",
    choices: ["Rent expenses", "Repair expenses", "Utilities"],
    meanings: ["地代家賃", "修繕費", "水道光熱費"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用'
  },
  {
    id: 61,
    question: "Research and development expenditures are recorded as (　).",
    translation: "研究開発支出は研究開発費として記録される。",
    choices: ["Research and development expenses", "Advertising expenses", "Commission expenses"],
    meanings: ["研究開発費", "広告宣伝費", "支払手数料"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用'
  },
  {
    id: 62,
    question: "Uncollectible receivables are written off as (　).",
    translation: "回収不能な債権は貸倒損失として償却される。",
    choices: ["Bad debt expenses", "Provision of allowance for doubtful accounts", "Impairment losses"],
    meanings: ["貸倒損失", "貸倒引当金繰入額", "減損損失"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用'
  },
  {
    id: 63,
    question: "Minor miscellaneous costs are recorded as (　).",
    translation: "軽微な雑多な費用は雑費として記録される。",
    choices: ["Miscellaneous expenses", "Supplies expenses", "Communication expenses"],
    meanings: ["雑費", "消耗品費", "通信費"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '費用'
  },
  {
    id: 64,
    question: "The company's core business income is reported as (　).",
    translation: "会社の主たる事業収入は営業収益として報告される。",
    choices: ["Operating revenue", "Net sales", "Interest income"],
    meanings: ["営業収益", "売上高", "受取利息"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '収益'
  },
  {
    id: 65,
    question: "Banks earn (　) from lending money to customers.",
    translation: "銀行は顧客への貸付から受取利息を得る。",
    choices: ["Interest income", "Dividend income", "Operating revenue"],
    meanings: ["受取利息", "受取配当金", "営業収益"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '収益'
  },
  {
    id: 66,
    question: "Shareholders receive (　) as a return on their investment.",
    translation: "株主は投資のリターンとして受取配当金を受け取る。",
    choices: ["Dividend income", "Interest income", "Net sales"],
    meanings: ["受取配当金", "受取利息", "売上高"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '収益'
  },
  {
    id: 67,
    question: "When the yen weakens, exporters recognize (　).",
    translation: "円安時に輸出業者は為替差益を計上する。",
    choices: ["Foreign exchange gains", "Net sales", "Operating revenue"],
    meanings: ["為替差益", "売上高", "営業収益"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '収益'
  },
  {
    id: 68,
    question: "Selling equipment above book value results in (　).",
    translation: "帳簿価額を上回る価格で設備を売却すると固定資産売却益が生じる。",
    choices: ["Gain on sale of non-current assets", "Interest income", "Operating revenue"],
    meanings: ["固定資産売却益", "受取利息", "営業収益"],
    answer: 0,
    category: '勘定科目等',
    source: 'user-provided list',
    subcategory: '収益'
  }
];
